name: Python Build

on: [push]

jobs:
  python-build:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Run image
        uses: abatilo/actions-poetry@v2
      
      - name: Install dependencies
        run: make install
      
      - name: Security Validation
        run: make security
      
      - name: Run tests 
        run: make test
      
      - name: Upload pytest test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: reports/junit.xml
      
      - name: Release
       # if: github.ref != 'refs/heads/main'
        uses: ./.github/workflows/python-release.yaml
        secrets:
          CICD_GIT_TOKEN: ${{ secrets.CICD_GIT_TOKEN }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}