name: Python Release

on:
  workflow_call:
    secrets:
      CICD_GIT_TOKEN:
        required: true

jobs:
  python-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CICD_GIT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Run image
        uses: abatilo/actions-poetry@v2
      
      - name: Configure git
        run: |
          git config --global user.name 'CICD'
          git config --global user.email 'actions@github.com'
          git push
      
      - name: Bump release version
        run: |
          export NEW_VERSION=$(poetry version -s)
          git commit -am "[skip ci] Bumping to version $NEW_VERSION"
      
      - name: Preparing to the next version
        run: |
          export NEW_VERSION=$(poetry version -s)
          git commit -am "[skip ci] PreRelease to $NEW_VERSION"
      
      - name: Tagging
        if: github.ref == 'refs/heads/main'
        run: |
          export NEW_VERSION=$(poetry version -s)
          git tag -a $NEW_VERSION -m $NEW_VERSION

      - name: Push results
        run: |
          git push "https://$GITHUB_ACTOR:${{ secrets.CICD_GIT_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git push "https://$GITHUB_ACTOR:${{ secrets.CICD_GIT_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --tags