name: Python Build

on:
  workflow_call:

jobs:
  python-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Remove pre views config
        run: rm pyproject.toml
      
      - uses: actions/download-artifact@v3
        with:
          name: pyproject
          path: pyproject.toml
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Run image
        uses: abatilo/actions-poetry@v2
      
      - name: Install dependencies
        run: make install
      
      - name: Security Validation
        run: make security
      
      - name: Run tests 
        run: make test
      
      - name: Upload pytest test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: reports/junit.xml