name: Python Workflow

on: [push]

jobs:
  python-versioning-preparation:
    uses: ./.github/workflows/python-versioning-preparation.yaml

  python-build:
    needs: python-versioning-preparation
    uses: ./.github/workflows/python-build.yaml

  python-publish:
    uses: ./.github/workflows/python-publish.yaml
    needs: python-build
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

  python-versioning-commit:
    uses: ./.github/workflows/python-release.yaml
    needs: python-publish
    secrets:
      CICD_GIT_TOKEN: ${{ secrets.CICD_GIT_TOKEN }}
